name: Auto Merge Owner

on:
  pull_request:
    types: [opened, reopened]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Merginator 2
      uses: managedkaos/merge-pull-request@v2.2.0
  
